apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0sControlPlane
metadata:
  name: {{ include "k0scontrolplane.name" . }}
  namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version }}
  k0sConfigSpec:
    {{- if .Values.singleArtifactSource.enabled }}
    downloadURL: "{{ .Values.singleArtifactSource.k0sURL }}/k0s-{{ .Values.k0s.version }}-amd64"
    {{- end }}
    preStartCommands:
    {{- with .Values.controlPlane.preStartCommands }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    args:
      - --enable-worker
      - --enable-cloud-provider
      - --kubelet-extra-args="--cloud-provider=external"
      - --disable-components=konnectivity-server
    files:
    {{- if .Values.controlPlane.files }}
      {{- toYaml .Values.controlPlane.files | nindent 6 }}
    {{- end }}
    k0s:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        telemetry:
          enabled: {{ .Values.k0s.telemetry.enabled }}
        api:
          extraArgs:
            anonymous-auth: "true"
            {{- with .Values.k0s.api.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        network:
          podCIDR: {{ index .Values.clusterNetwork.pods.cidrBlocks 0 }}
          serviceCIDR: {{ index .Values.clusterNetwork.services.cidrBlocks 0 }}
          provider: calico
          calico:
            mode: vxlan
            vxlanPort: {{ .Values.k0s.network.vxlanPort }}
            envVars:
              CALICO_IPV4POOL_CIDR: "{{ index .Values.clusterNetwork.pods.cidrBlocks 0 }}"
              CLUSTER_TYPE: "k8s"
              CALICO_IPV4POOL_IPIP: "Never"
              CALICO_IPV4POOL_VXLAN: "Always"
              FELIX_VXLANPORT: "{{ .Values.k0s.network.vxlanPort }}"
              FELIX_ALLOWVXLANPACKETSFROMWORKLOADS: "true"
        images:
        {{- if .Values.singleArtifactSource.enabled }}
          metricsserver:
            image: "{{ .Values.singleArtifactSource.registry}}/metrics-server"
          kubeproxy:
            image: "{{ .Values.singleArtifactSource.registry}}/kube-proxy"
          coredns:
            image: "{{ .Values.singleArtifactSource.registry}}/coredns"
          pause:
            image: "{{ .Values.singleArtifactSource.registry}}/pause"
          calico:
            cni:
              image: "{{ .Values.singleArtifactSource.registry}}/calico-cni"
            node:
              image: "{{ .Values.singleArtifactSource.registry}}/calico-node"
            kubecontrollers:
              image: "{{ .Values.singleArtifactSource.registry}}/calico-kube-controllers"
        {{- else }}
          repository: "{{ .Values.k0s.images.repository }}"
        {{- end }}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: KubevirtMachineTemplate
      name: {{ include "kubevirtmachinetemplate.controlplane.name" . }}
      namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
