name: "K0s Github Pages Binaries"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Source repository to clone and build from'
        required: true
        default: 'k0sproject/k0s'
        type: choice
        options:
          - 'k0sproject/k0s'
          - 'k0rdent-oot/k0s'
      ref:
        description: 'Git ref to build from (branch, tag, or commit SHA)'
        required: false
        default: 'main'
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  MAKEFLAGS: -j

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
            target_os: linux
            target_arch: amd64
          - arch: arm64
            runner: ubuntu-24.04-arm
            target_os: linux
            target_arch: arm64

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref || github.ref }}
          persist-credentials: false

      - name: Prepare
        id: build-prepare
        run: |
          .github/workflows/prepare-build-env.sh
          echo executable-suffix="" >>"$GITHUB_OUTPUT"

      - name: Build
        run: |
          export TARGET_OS=${{ matrix.target_os }}
          export TARGET_ARCH=${{ matrix.target_arch }}

          make clean || true
          make bindata
          make --touch codegen
          make build

          mkdir -vp binaries
          mv -v k0s${{ steps.build-prepare.outputs.executable-suffix }} binaries/k0s-${{ matrix.target_os }}-${{ matrix.arch }}${{ steps.build-prepare.outputs.executable-suffix }}
          cd binaries && sha256sum k0s-${{ matrix.target_os }}-${{ matrix.arch }}${{ steps.build-prepare.outputs.executable-suffix }} > k0s-${{ matrix.target_os }}-${{ matrix.arch }}${{ steps.build-prepare.outputs.executable-suffix }}.sha256

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: k0s-${{ matrix.target_os }}-${{ matrix.arch }}
          path: binaries/
          retention-days: 1

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-24.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Organize binaries
        run: |
          mkdir -p deploy/binaries
          cp -r artifacts/*/* deploy/binaries/

      - name: Create index page
        run: |
          cat > deploy/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>k0s Downloads</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
                  h1 { color: #333; }
                  h2 { color: #555; margin-top: 30px; }
                  ul { list-style-type: none; padding: 0; }
                  li { margin: 8px 0; }
                  a { text-decoration: none; color: #0066cc; font-weight: bold; }
                  a:hover { text-decoration: underline; }
                  .binary-section { background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0; }
                  .hash-link { font-size: 0.9em; margin-left: 10px; color: #666; }
                  .source-info { background: #fff3cd; padding: 10px; border-radius: 5px; margin: 10px 0; border-left: 4px solid #ffc107; }
                  .build-info { background: #d4edda; padding: 10px; border-radius: 5px; margin: 10px 0; border-left: 4px solid #28a745; }
              </style>
          </head>
          <body>
              <h1>k0s Binary Downloads</h1>

              <div class="binary-section">
                  <h2>📦 Binaries</h2>
                  <p>Download the appropriate binary for your platform:</p>
                  <ul>
                      <li>🐧 <a href="binaries/k0s-linux-amd64">k0s-linux-amd64</a>
                          <span class="hash-link">
                              [<a href="binaries/k0s-linux-amd64.sha256">SHA256</a>]
                          </span>
                      </li>
                      <li>🐧 <a href="binaries/k0s-linux-arm64">k0s-linux-arm64</a>
                          <span class="hash-link">
                              [<a href="binaries/k0s-linux-arm64.sha256">SHA256</a>]
                          </span>
                      </li>
                  </ul>
              </div>

          </body>
          </html>
          EOF

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'deploy'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
