name: Mirror Images to OCI Registry

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  mirror-images:
    runs-on: ubuntu-latest

    steps:
      - name: Install Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | skopeo login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Mirror registry.k8s.io/pause:3.10
        run: |
          skopeo copy \
            docker://registry.k8s.io/pause:3.10 \
            docker://ghcr.io/${{ github.repository }}/pause:3.10

      - name: Mirror registry.k8s.io/metrics-server/metrics-server:v0.7.2
        run: |
          skopeo copy \
            docker://registry.k8s.io/metrics-server/metrics-server:v0.7.2 \
            docker://ghcr.io/${{ github.repository }}/metrics-server:v0.7.2
